"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_red)\
$os\
$username\
[](bg:color_yellow fg:color_red)\
$directory\
[](fg:color_yellow bg:color_blue)\
$git_branch\
$git_status\
[](fg:color_blue bg:color_green)\
$c\
$rust\
$golang\
$nodejs\
$dotnet\
$php\
$java\
$kotlin\
$haskell\
[](fg:color_green bg:color_purple)\
$docker_context\
$conda\
$python\
[](fg:color_purple bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$sudo\
$line_break$character"""

palette = 'gruvbox_dark'

# ~/.config/starship.toml

[sudo]
style = 'bold green'
symbol = '👩‍💻'
disabled = false
format = '[$symbol]($style)'

[palettes.gruvbox_dark]
color_fg0 = '#f0f0f0'
color_fg1 = '#090909'
color_bg1 = '#737373'
color_bg3 = '#808080'
color_blue = '#00A4EF'
color_aqua = '#17ACF0'
color_green = '#7FBA00'
color_orange = '#F25022'
color_purple = '#505AC9'
color_red = '#C1330B'
color_yellow = '#FFB900'
color_white = '#FFFFFF'

[os]
disabled = false
style = "bg:color_red fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_red fg:color_fg0"
style_root = "bg:color_red fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 100
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"code" = "󰲋 "
"github" = " "
"node_modules" = " "
".git" = "󰊢 "
"src" = " "
"dist" = " "

[git_branch]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_blue)]($style)'

[git_status]
style = "bg:color_blue"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_blue)]($style)'

[nodejs]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[dotnet]
symbol = ""
style = 'bg:color_green'
heuristic = false
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[c]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[rust]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[golang]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[php]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[java]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[kotlin]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[haskell]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[python]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_purple)]($style)'

[docker_context]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_purple)]($style)'

[conda]
style = "bg:color_purple"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_purple)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
